header:
  version: 11

bblayers_conf_header:
  standard: |
    POKY_BBLAYERS_CONF_VERSION = "2"
    BBPATH = "${TOPDIR}"
    BBFILES ?= ""
    YOCTOROOT = "${@os.path.abspath(os.path.join("${TOPDIR}", os.pardir))}"

local_conf_header:
  standard: |
    BB_GENERATE_MIRROR_TARBALLS = "1"
    BOOT_DELAY = "0"
    BOOT_DELAY_MS = "0"

  buildinfo:
    INHERIT += " rm_work"
   
