header:
  version: 11

repos:
  poky:
    url: https://git.yoctoproject.org/poky
    path: poky
    branch: kirkstone
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp:

  meta-raspberrypi:
    url: https://git.yoctoproject.org/meta-raspberrypi
    path: meta-raspberrypi
    branch: kirkstone

  meta-openembedded:
    url: https://git.openembedded.org/meta-openembedded
    path: meta-openembedded
    branch: kirkstone
    layers:
      meta-filesystems:
      meta-gnome:
      meta-initramfs:
      meta-multimedia:
      meta-networking:
      meta-oe:
      meta-perl:
      meta-python:
      meta-webserver:
      meta-xfce:

  boot-doc:
    url: https://github.com/waelkarman/bunch-linux-boot-sequence.git
    branch: "main"
