name: Build on Ubuntu Latest

on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Setup Python 
        run: pip3 install kas
      - name: Install required deps
        run: sudo apt install chrpath diffstat zstd
      - name: Checkout and build
        run: kas checkout kas/bunch-linux-demo.yml; bitbake bunch-linux-demo
