name: Build on Local Host

on: [workflow_dispatch]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - run: echo "This job is now running on local host!"
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Setup Python 
        run: pip3 install kas
      - name: Install required deps
        run: sudo apt install chrpath diffstat zstd
      - name: Checkout and build
        run: cd $GITHUB_WORKSPACE/bunch-linux-manifests; source poky/oe-init-build-env; bitbake bunch-linux-demo
